services:
  waterCarrier_db:
    image: mysql:9.3.0
    container_name: waterCarrier_db
    env_file:
        - .env
    environment:
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}   
        MYSQL_DATABASE: ${MYSQL_DATABASE}
        MYSQL_USER: ${MYSQL_USER}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
        - "${MYSQL_TCP_PORT}:3306"
    volumes:
        - waterCarrier_data:/var/lib/mysql
        - ./mysql-init:/docker-entrypoint-initdb.d
        - ./custom.cnf:/etc/mysql/conf.d/custom.cnf
    command: [
      "--character-set-server=utf8mb4",
      "--collation-server=utf8mb4_unicode_ci",
      "--init-connect=SET NAMES utf8mb4" 
    ]
    restart: unless-stopped

volumes:
    waterCarrier_data:
        